//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WININFO.RC
//
#define SELINVIEW                       1
#define ADDRINVIEW                      1
#define IDS_XTASK12                     509
#define IDC_IDT                         1000
#define IDC_PMIV                        1002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
